# Этап сборки
FROM node:20-bullseye AS builder

WORKDIR /app

ENV VITE_API_BASE_URL=/api/
ENV VITE_WS_BASE_URL=ws://81.17.154.44:8001/api/v1/

# Устанавливаем pnpm
RUN npm install -g pnpm

# Копируем файлы зависимостей
COPY package.json pnpm-lock.yaml ./

# Устанавливаем зависимости
RUN pnpm install --frozen-lockfile

# Копируем исходный код
COPY . .

# Собираем приложение
RUN pnpm run build

CMD ["npm", "run", "start"]