export const MOCK_DATA = {
    users: [
        {
            id: 1,
            name: "Максим",
            email: "max@example.com",
        },
        {
            id: 2,
            name: "Аня",
            email: "anya@example.com",
        },
    ],
    profiles: [
        {
            id: 1,
            userId: 1,
            name: "Личный",
            type: "personal",
        },
        {
            id: 2,
            userId: 1,
            name: "Семья",
            type: "family",
        },
        {
            id: 3,
            userId: 2,
            name: "Аня",
            type: "personal",
        },
    ],
    categories: [
        {
            id: "salary",
            name: "Зарплата",
            type: "income",
        },
        {
            id: "food",
            name: "Еда и продукты",
            type: "expense",
        },
        {
            id: "cafes",
            name: "Кафе и рестораны",
            type: "expense",
        },
        {
            id: "transport",
            name: "Транспорт",
            type: "expense",
        },
        {
            id: "subscriptions",
            name: "Подписки",
            type: "expense",
        },
        {
            id: "rent",
            name: "Аренда",
            type: "expense",
        },
        {
            id: "other",
            name: "Прочее",
            type: "expense",
        },
    ],
    sessions: [
        {
            id: 1,
            userId: 1,
            profileId: 1,
            title: "Ноябрь 2025 — личные финансы",
            createdAt: "2025-12-05T10:00:00.000Z",
            status: "ready",
            mlSessionId: "ml-abc123",
            dateFrom: "2025-11-01",
            dateTo: "2025-11-30",
            fileName: "transactions_nov_personal.csv",
        },
        {
            id: 2,
            userId: 1,
            profileId: 2,
            title: "Ноябрь 2025 — семья",
            createdAt: "2025-12-04T19:00:00.000Z",
            status: "ready",
            mlSessionId: "ml-def456",
            dateFrom: "2025-11-01",
            dateTo: "2025-11-30",
            fileName: "transactions_nov_family.csv",
        },
        {
            id: 3,
            userId: 1,
            profileId: 1,
            title: "Октябрь 2025 — личные финансы",
            createdAt: "2025-11-05T09:30:00.000Z",
            status: "ready",
            mlSessionId: "ml-ghi789",
            dateFrom: "2025-10-01",
            dateTo: "2025-10-31",
            fileName: "transactions_oct_personal.csv",
        },
    ],
    sessionSummaries: [
        {
            id: 1,
            sessionId: 1,
            totalIncome: 150000,
            totalExpense: 112000,
            netChange: 38000,
            currency: "RUB",
            avgDailyExpense: 3733,
            projectedCushion: 210000,
        },
        {
            id: 2,
            sessionId: 2,
            totalIncome: 220000,
            totalExpense: 185000,
            netChange: 35000,
            currency: "RUB",
            avgDailyExpense: 6167,
            projectedCushion: 320000,
        },
        {
            id: 3,
            sessionId: 3,
            totalIncome: 145000,
            totalExpense: 118000,
            netChange: 27000,
            currency: "RUB",
            avgDailyExpense: 3806,
            projectedCushion: 180000,
        },
    ],
    budgets: [
        {
            id: 1,
            userId: 1,
            profileId: 1,
            month: "2025-11",
            categoryId: "food",
            limit: 25000,
        },
        {
            id: 2,
            userId: 1,
            profileId: 1,
            month: "2025-11",
            categoryId: "cafes",
            limit: 12000,
        },
        {
            id: 3,
            userId: 1,
            profileId: 1,
            month: "2025-11",
            categoryId: "transport",
            limit: 8000,
        },
        {
            id: 4,
            userId: 1,
            profileId: 1,
            month: "2025-11",
            categoryId: "subscriptions",
            limit: 5000,
        },
        {
            id: 5,
            userId: 1,
            profileId: 1,
            month: "2025-11",
            categoryId: "rent",
            limit: 40000,
        },
    ],
    categoryOverrides: [
        {
            id: 1,
            sessionId: 1,
            transactionId: "tx-2025-11-05-001",
            mlCategory: "other",
            userCategory: "transport",
            comment: "Такси до офиса, раньше относилось к 'Прочее'",
        },
        {
            id: 2,
            sessionId: 1,
            transactionId: "tx-2025-11-10-002",
            mlCategory: "food",
            userCategory: "cafes",
            comment: "Ресторан с друзьями",
        },
        {
            id: 3,
            sessionId: 2,
            transactionId: "tx-2025-11-15-010",
            mlCategory: "other",
            userCategory: "subscriptions",
            comment: "Spotify Family",
        },
    ],
    rules: [
        {
            id: 1,
            userId: 1,
            profileId: 1,
            matchType: "contains",
            field: "description",
            value: "YANDEX.TAXI",
            categoryId: "transport",
        },
        {
            id: 2,
            userId: 1,
            profileId: 1,
            matchType: "contains",
            field: "description",
            value: "DELIVERY CLUB",
            categoryId: "food",
        },
        {
            id: 3,
            userId: 1,
            profileId: 1,
            matchType: "contains",
            field: "description",
            value: "SPOTIFY",
            categoryId: "subscriptions",
        },
    ],
    notificationSettings: [
        {
            id: 1,
            userId: 1,
            type: "budget_limit",
            threshold: 0.8,
            enabled: true,
        },
        {
            id: 2,
            userId: 1,
            type: "low_cushion",
            threshold: 1.0,
            enabled: true,
        },
        {
            id: 3,
            userId: 1,
            type: "anomaly",
            threshold: 3.0,
            enabled: false,
        },
    ],
    notificationsLog: [
        {
            id: 1,
            userId: 1,
            sessionId: 1,
            type: "budget_limit",
            payload: {
                categoryId: "cafes",
                current: 11500,
                limit: 12000,
                month: "2025-11",
            },
            createdAt: "2025-11-27T18:30:00.000Z",
            read: false,
        },
        {
            id: 2,
            userId: 1,
            sessionId: 1,
            type: "low_cushion",
            payload: {
                currentCushion: 75000,
                recommendedCushion: 120000,
            },
            createdAt: "2025-11-20T09:10:00.000Z",
            read: true,
        },
    ],
    goals: [
        {
            id: 1,
            userId: 1,
            profileId: 1,
            type: "cushion",
            title: "Финансовая подушка 3× расходов",
            targetAmount: 300000,
            targetDate: "2026-06-01",
            currentAmount: 180000,
            priority: "high",
            status: "in_progress",
        },
        {
            id: 2,
            userId: 1,
            profileId: 1,
            type: "travel",
            title: "Поездка в Европу",
            targetAmount: 150000,
            targetDate: "2026-03-15",
            currentAmount: 40000,
            priority: "medium",
            status: "in_progress",
        },
    ],
    subscriptions: [
        {
            id: 1,
            userId: 1,
            profileId: 1,
            merchant: "SPOTIFY",
            amount: 499,
            currency: "RUB",
            period: "monthly",
            nextChargeDate: "2025-12-12",
            active: true,
            categoryId: "subscriptions",
        },
        {
            id: 2,
            userId: 1,
            profileId: 1,
            merchant: "NETFLIX",
            amount: 999,
            currency: "RUB",
            period: "monthly",
            nextChargeDate: "2025-12-03",
            active: false,
            categoryId: "subscriptions",
        },
        {
            id: 3,
            userId: 1,
            profileId: 2,
            merchant: "YANDEX.PLUS",
            amount: 299,
            currency: "RUB",
            period: "monthly",
            nextChargeDate: "2025-12-10",
            active: true,
            categoryId: "subscriptions",
        },
    ],
    tips: [
        {
            id: 1,
            title: "Проверьте подписки",
            body: "Раз в месяц просматривайте список подписок и отключайте те, которыми давно не пользовались.",
            tag: "subscriptions",
        },
        {
            id: 2,
            title: "Лимит на кафе",
            body: "Выделите фиксированную сумму на кафе и рестораны и придерживайтесь её в течение месяца.",
            tag: "cafes",
        },
        {
            id: 3,
            title: "Правило 50/30/20",
            body: "50% дохода — на базовые нужды, 30% — на желания, 20% — на сбережения.",
            tag: "cushion",
        },
    ],
    lessons: [
        {
            id: 1,
            title: "Базовые принципы личного бюджета",
            description: "Короткий курс о том, как распределять доходы и контролировать расходы.",
            tag: "basics",
            estimatedMinutes: 15,
        },
        {
            id: 2,
            title: "Как сформировать финансовую подушку",
            description: "Зачем нужна подушка безопасности и как к ней идти.",
            tag: "cushion",
            estimatedMinutes: 10,
        },
    ],
    quizQuestions: [
        {
            id: 1,
            lessonId: 1,
            question: "Какой процент дохода рекомендуется откладывать на сбережения?",
            options: ["5–10%", "10–20%", "20% и более"],
            correctIndex: 2,
        },
        {
            id: 2,
            lessonId: 2,
            question: "На сколько месяцев расходов обычно рекомендуют иметь подушку?",
            options: ["1–2 месяца", "3–6 месяцев", "12 месяцев"],
            correctIndex: 1,
        },
    ],
    quizResults: [
        {
            id: 1,
            userId: 1,
            lessonId: 1,
            score: 100,
            completedAt: "2025-11-10T20:00:00.000Z",
        },
    ],
    achievements: [
        {
            id: 1,
            code: "first_session",
            title: "Первый анализ",
            description: "Вы провели свой первый анализ финансов.",
            conditionType: "sessions_count",
            conditionPayload: {
                min: 1,
            },
        },
        {
            id: 2,
            code: "month_without_overspend",
            title: "Месяц без перерасхода",
            description: "Ни одну категорию бюджета не превысили за месяц.",
            conditionType: "no_overspend_months",
            conditionPayload: {
                min: 1,
            },
        },
        {
            id: 3,
            code: "cushion_2x",
            title: "Подушка 2× расходов",
            description: "Сформирована подушка > 2× средних месячных расходов.",
            conditionType: "cushion_multiplier",
            conditionPayload: {
                min: 2.0,
            },
        },
    ],
    userAchievements: [
        {
            id: 1,
            userId: 1,
            achievementId: 1,
            unlockedAt: "2025-10-05T09:35:00.000Z",
        },
    ],
    challenges: [
        {
            id: 1,
            title: "Неделя без доставки еды",
            description: "Не заказывайте доставку еды в течение 7 дней.",
            startDate: "2025-11-01",
            endDate: "2025-11-07",
            type: "no_category",
            payload: {
                categoryId: "cafes",
            },
        },
        {
            id: 2,
            title: "Месяц без минуса",
            description: "За месяц ваши доходы должны быть не меньше расходов.",
            startDate: "2025-11-01",
            endDate: "2025-11-30",
            type: "net_positive",
            payload: {
                minNetChange: 0,
            },
        },
    ],
    scenarios: [
        {
            id: 1,
            userId: 1,
            sessionId: 1,
            name: "Меньше кафе на 30%",
            description: "Сократить траты на кафе и рестораны на 30%.",
            changes: [
                {
                    categoryId: "cafes",
                    multiplier: 0.7,
                },
            ],
            resultDiff: {
                savedPerMonth: 3500,
                cushionAfter6Months: 230000,
            },
        },
        {
            id: 2,
            userId: 1,
            sessionId: 1,
            name: "Отказ от лишних подписок",
            description: "Отключить Netflix и часть других подписок.",
            changes: [
                {
                    categoryId: "subscriptions",
                    delta: -800,
                },
            ],
            resultDiff: {
                savedPerMonth: 800,
                savedPerYear: 9600,
            },
        },
    ],
    feedback: [
        {
            id: 1,
            userId: 1,
            sessionId: 1,
            transactionId: "tx-2025-11-10-002",
            feedbackType: "category",
            rating: 2,
            comment: "Ресторан попал в 'Еда', но я считаю это 'Кафе'.",
        },
        {
            id: 2,
            userId: 1,
            sessionId: 1,
            transactionId: null,
            feedbackType: "recommendation",
            rating: 5,
            comment: "Совет про подписки оказался полезным, отменил Netflix.",
        },
    ],
};
